# Generated by Django 5.1 on 2024-09-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_carrito_tipousuario_itemcarrito_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='juegos.categoria'),
        ),
    ]
