# Generated by Django 5.1 on 2024-09-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0005_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.carrito'),
        ),
    ]
